name: Patch Workflow

on: 
  push:
    branches: [ main ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up environment variables
      run: echo "PATCHVBMETAFLAG=true" >> $GITHUB_ENV
      shell: bash

    - name: Load config variables
      id: config
      run: |
        # Assuming the config.env file is in the root of the repository
        cat config.env | xargs -n1 | while read line; do
          echo "Setting $line"
          echo "$line" >>$GITHUB_ENV
        done
      shell: bash

    - name: Download files
      run: |
        wget -O magiskboot $MAGISKBOOT_URL
        wget -O kpimg-android $KP_IMG_URL
        wget -O kptools-linux $KP_TOOLS_URL
        wget -O boot.img $BOOT_URL
        chmod +x magiskboot kptools-linux
      shell: bash

    - name: Rename files
      run: |
        mv kptools-linux kptools
        mv kpimg-android kpimg
        chmod +x magiskboot kptools
      shell: bash

    - name: Patch commands
      run: |
        ./magiskboot unpack boot.img
        mv kernel kernel.ori
        ./kptools -p -i kernel.ori -k kpimg -s $SKEY -o kernel
        ./magiskboot repack boot.img
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: new-boot.img
        path: new-boot.img
        retention-days: 1
